# Generated by Django 4.2.27 on 2026-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_queue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
